[main]
font=JetBrains Mono:size=10
pad=10x10 center

[colors-dark]
background=1e1b18
foreground=faf5e8

# Normal
regular0=2a2521
regular1=e27d93
regular2=a3be8c
regular3=e8c547
regular4=3b939c
regular5=f0a7b8
regular6=8abeb7
regular7=faf5e8

# Bright
bright0=5a524c
bright1=f0a7b8
bright2=b5d19c
bright3=fbe385
bright4=51b1bc
bright5=f7c1cd
bright6=9ececa
bright7=ffffff

[key-bindings]
clipboard-copy=Control+Shift+c Control+c
clipboard-paste=Control+Shift+v Control+v
